from .shallownet import ShallowNet
from .lenet import LeNet
from .minivggnet import MiniVGGNet
from .fcheadnet import FCHeadNet
from .alexnet import AlexNet
from .minigooglenet import MiniGoogLeNet
from .deepergooglenet import DeeperGoogLeNet
from .resnet import ResNet
from .agegender import AgeGenderNet
from .saliencynet import SaliencyNet